import { startOfMonth, addDays, setHours } from "date-fns";

const baseDate = startOfMonth(new Date());

export const initialEvents = [
  {
    id: "1",
    title: "Team Meeting",
    start: setHours(addDays(baseDate, 1), 9).toISOString(),
    end: setHours(addDays(baseDate, 1), 10).toISOString(),
    color: "#22c55e",
  },
  {
    id: "2",
    title: "Project Deadline",
    start: addDays(baseDate, 3).toISOString(),
    end: addDays(baseDate, 3).toISOString(),
    color: "#3b82f6",
  },
  {
    id: "3",
    title: "Client Call",
    start: setHours(addDays(baseDate, 4), 14).toISOString(),
    end: setHours(addDays(baseDate, 4), 15).toISOString(),
    color: "#f97316",
  },
  {
    id: "4",
    title: "Design Review",
    start: setHours(addDays(baseDate, 5), 11).toISOString(),
    end: setHours(addDays(baseDate, 5), 12).toISOString(),
    color: "#8b5cf6",
  },
  {
    id: "5",
    title: "Sprint Planning",
    start: setHours(addDays(baseDate, 6), 10).toISOString(),
    end: setHours(addDays(baseDate, 6), 11).toISOString(),
    color: "#ec4899",
  },
  {
    id: "6",
    title: "Workshop",
    start: setHours(addDays(baseDate, 8), 13).toISOString(),
    end: setHours(addDays(baseDate, 8), 16).toISOString(),
    color: "#10b981",
  },
  {
    id: "7",
    title: "Code Review",
    start: setHours(addDays(baseDate, 10), 15).toISOString(),
    end: setHours(addDays(baseDate, 10), 16).toISOString(),
    color: "#3b82f6",
  },
  {
    id: "8",
    title: "Marketing Meeting",
    start: setHours(addDays(baseDate, 12), 9).toISOString(),
    end: setHours(addDays(baseDate, 12), 10).toISOString(),
    color: "#f87171",
  },
  {
    id: "9",
    title: "Product Launch",
    start: addDays(baseDate, 14).toISOString(),
    end: addDays(baseDate, 14).toISOString(),
    color: "#fbbf24",
  },
  {
    id: "10",
    title: "Team Lunch",
    start: setHours(addDays(baseDate, 16), 12).toISOString(),
    end: setHours(addDays(baseDate, 16), 13).toISOString(),
    color: "#0ea5e9",
  },
  {
    id: "11",
    title: "One-on-One",
    start: setHours(addDays(baseDate, 18), 11).toISOString(),
    end: setHours(addDays(baseDate, 18), 11.5).toISOString(),
    color: "#a855f7",
  },
  {
    id: "12",
    title: "Board Meeting",
    start: setHours(addDays(baseDate, 20), 10).toISOString(),
    end: setHours(addDays(baseDate, 20), 12).toISOString(),
    color: "#f43f5e",
  },
  {
    id: "13",
    title: "Client Feedback",
    start: setHours(addDays(baseDate, 22), 14).toISOString(),
    end: setHours(addDays(baseDate, 22), 15).toISOString(),
    color: "#22c55e",
  },
  {
    id: "14",
    title: "Design Handoff",
    start: setHours(addDays(baseDate, 24), 9).toISOString(),
    end: setHours(addDays(baseDate, 24), 10).toISOString(),
    color: "#3b82f6",
  },
  {
    id: "15",
    title: "Retrospective",
    start: setHours(addDays(baseDate, 26), 16).toISOString(),
    end: setHours(addDays(baseDate, 26), 17).toISOString(),
    color: "#f97316",
  },
];
