export const orders = [
  {
    id: "2001",
    customer: "John Miller",
    email: "john.miller@email.com",
    items: 2,
    total: 199.99,
    paymentMethod: "Credit Card",
    status: "Processing",
    createdAt: "2024-01-12",
  },
  {
    id: "2002",
    customer: "Emily Johnson",
    email: "emily.johnson@email.com",
    items: 1,
    total: 79.99,
    paymentMethod: "PayPal",
    status: "Delivered",
    createdAt: "2024-01-08",
  },
  {
    id: "2003",
    customer: "Michael Brown",
    email: "michael.brown@email.com",
    items: 4,
    total: 459.5,
    paymentMethod: "Credit Card",
    status: "Shipped",
    createdAt: "2024-01-18",
  },
  {
    id: "2004",
    customer: "Sarah Wilson",
    email: "sarah.wilson@email.com",
    items: 3,
    total: 129.0,
    paymentMethod: "Apple Pay",
    status: "Pending",
    createdAt: "2024-01-21",
  },
  {
    id: "2005",
    customer: "Daniel Thompson",
    email: "daniel.thompson@email.com",
    items: 5,
    total: 899.99,
    paymentMethod: "Credit Card",
    status: "Paid",
    createdAt: "2024-01-25",
  },
  {
    id: "2006",
    customer: "Olivia Anderson",
    email: "olivia.anderson@email.com",
    items: 1,
    total: 49.99,
    paymentMethod: "PayPal",
    status: "Cancelled",
    createdAt: "2024-01-27",
  },
  {
    id: "2007",
    customer: "James Taylor",
    email: "james.taylor@email.com",
    items: 6,
    total: 1199.0,
    paymentMethod: "Credit Card",
    status: "Processing",
    createdAt: "2024-02-01",
  },
  {
    id: "2008",
    customer: "Sophia Martinez",
    email: "sophia.martinez@email.com",
    items: 2,
    total: 249.99,
    paymentMethod: "Google Pay",
    status: "Delivered",
    createdAt: "2024-02-03",
  },
  {
    id: "2009",
    customer: "William Davis",
    email: "william.davis@email.com",
    items: 3,
    total: 349.0,
    paymentMethod: "Credit Card",
    status: "Shipped",
    createdAt: "2024-02-05",
  },
  {
    id: "2010",
    customer: "Emma Clark",
    email: "emma.clark@email.com",
    items: 2,
    total: 159.99,
    paymentMethod: "PayPal",
    status: "Pending",
    createdAt: "2024-02-07",
  },
];
