export const pageTitles = {
  "/dashboard": "Dashboard",
  "/analytics": "Analytics",
  "/users": "Users",
  "/e-commerce": "E-commerce",
  "/e-commerce/products": "Products",
  "/e-commerce/orders": "Orders",
  "/e-commerce/customers": "Customers",
  "/inventory": "Inventory",
  "/transactions": "Transactions",
  "/messages": "Messages",
  "/calendar": "Calendar",
  "/reports": "Reports",
  "/settings": "Settings",
};

export const pageSubtitles = {
  "/dashboard": "Welcome back, John!       ",
  "/analytics": "Business overview         ",
  "/users": "Manage all users          ",
  "/e-commerce": "Store performance         ",
  "/e-commerce/products": "Manage products           ",
  "/e-commerce/orders": "Track all orders          ",
  "/e-commerce/customers": "Manage customers          ",
  "/inventory": "Track products            ",
  "/transactions": "Review all transactions   ",
  "/messages": "All messages              ",
  "/calendar": "Your events               ",
  "/reports": "Detailed reports          ",
  "/settings": "App settings              ",
};

export const searchPlaceholders = {
  "/dashboard": "Search anything...",
  "/analytics": "Search analytics data...",
  "/users": "Search users...",
  "/e-commerce": "",
  "/e-commerce/products": "Search products...",
  "/e-commerce/orders": "Search orders...",
  "/e-commerce/customers": "Search customers...",
  "/inventory": "Search products...",
  "/transactions": "Search transactions...",
  "/messages": "Search messages...",
  "/calendar": "Search events...",
  "/reports": "Search reports...",
  "/settings": "Search settings...",
};
