export const pageTitles = {
  "/dashboard": "Dashboard",
  "/analytics": "Analytics",
  "/users": "Users",
  "/e-commerce": "E-commerce",
  "/e-commerce/products": "Products",
  "/e-commerce/orders": "Orders",
  "/e-commerce/customers": "Customers",
  "/inventory": "Inventory",
  "/transactions": "Transactions",
  "/messages": "Messages",
  "/calendar": "Calendar",
  "/reports": "Reports",
  "/settings": "Settings",
};

export const pageSubtitles = {
  "/dashboard": "Welcome back, André!",
  "/analytics": "Business performance overview",
  "/users": "Manage and monitor all users",
  "/e-commerce": "Monitor your store performance",
  "/e-commerce/products": "View and manage all products",
  "/e-commerce/orders": "Track all orders",
  "/e-commerce/customers": "Manage your customers",
  "/inventory": "Track your products",
  "/transactions": "Review all transactions",
  "/messages": "See all messages",
  "/calendar": "Your schedule and events",
  "/reports": "Detailed reports and insights",
  "/settings": "Manage application settings",
};

export const searchPlaceholders = {
  "/dashboard": "Search anything...",
  "/analytics": "Search analytics data...",
  "/users": "Search users...",
  "/e-commerce": "",
  "/e-commerce/products": "Search products...",
  "/e-commerce/orders": "Search orders...",
  "/e-commerce/customers": "Search customers...",
  "/inventory": "Search products...",
  "/transactions": "Search transactions...",
  "/messages": "Search messages...",
  "/calendar": "Search events...",
  "/reports": "Search reports...",
  "/settings": "Search settings...",
};
