export const products = [
  {
    id: "prd_1a2b3c",
    name: "Wireless Headphones",
    category: "Electronics",
    price: 149.99,
    stock: 120,
    status: "Active",
    createdAt: "Feb 5, 2024",
    image: "/images/products/headphones.webp",
  },
  {
    id: "prd_4d5e6f",
    name: "Smartwatch Series 7",
    category: "Electronics",
    price: 299.99,
    stock: 75,
    status: "Active",
    createdAt: "Jan 22, 2024",
    image: "/images/products/smartwatch.webp",
  },
  {
    id: "prd_7g8h9i",
    name: "Leather Backpack",
    category: "Accessories",
    price: 89.99,
    stock: 45,
    status: "Active",
    createdAt: "Mar 1, 2024",
    image: "/images/products/leather_backpack.webp",
  },
  {
    id: "prd_0j1k2l",
    name: "Running Shoes",
    category: "Footwear",
    price: 129.99,
    stock: 200,
    status: "Active",
    createdAt: "Feb 12, 2024",
    image: "/images/products/running_shoes.webp",
  },
  {
    id: "prd_3m4n5o",
    name: "Bluetooth Speaker",
    category: "Electronics",
    price: 59.99,
    stock: 150,
    status: "Active",
    createdAt: "Jan 30, 2024",
    image: "/images/products/bluetooth_speaker.webp",
  },
  {
    id: "prd_6p7q8r",
    name: "Coffee Maker",
    category: "Home Appliances",
    price: 79.99,
    stock: 90,
    status: "Active",
    createdAt: "Feb 20, 2024",
    image: "/images/products/coffee_maker.webp",
  },
  {
    id: "prd_2v3w4x",
    name: "Desk Lamp",
    category: "Home Decor",
    price: 39.99,
    stock: 110,
    status: "Active",
    createdAt: "Feb 25, 2024",
    image: "/images/products/desk_lamp.webp",
  },
  {
    id: "prd_5y6z7a",
    name: "Water Bottle",
    category: "Accessories",
    price: 19.99,
    stock: 500,
    status: "Active",
    createdAt: "Mar 5, 2024",
    image: "/images/products/water_bottle.webp",
  },
  {
    id: "prd_8b9c0d",
    name: "Gaming Mouse",
    category: "Electronics",
    price: 49.99,
    stock: 80,
    status: "Active",
    createdAt: "Jan 15, 2024",
    image: "/images/products/gaming_mouse.webp",
  },
];
